version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/build:/usr/share/nginx/html # Adjust path as necessary
      - ./nginx.conf:/etc/nginx/nginx.conf # Custom NGINX config
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend # Adjust path as necessary
    ports:
      - "5000:5000"
